name: GMP_Auto
on:
  workflow_dispatch:
jobs:
  check_completion:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with: 
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./dependencies/requirements.txt
        sudo cp -p ./settings_profiles/settings_auto_github_workflow.json ./settings.json
    - name: GMP Auto Complete
      run: |
        python ./multi_stu.py